#! /bin/bash -e

HTPASSWD_FILE="htpasswd_file"
echo "Creating : $HTPASSWD_FILE"

# htpasswd
# --------
# -c = Create a new file (the first command to create the file)..
# -B = Use bcrypt encryption for passwords..
# -b = Use batch mode (danger)..

USER="admin"
PASSWORD=`cat $HOME/.passwd/_clusters/users/$USER.passwd`
htpasswd -c -B -b $HTPASSWD_FILE $USER $PASSWORD

USER="alice"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD

USER="bob"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD

for a in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32; do
  USER="student$a"
  PASSWORD=`cat $HOME/.passwd/_clusters/users/$USER.passwd`
  htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD
done 

CUSTOM_RESOURCE_FILE="/tmp/customer_resource.yaml"
cat <<EOF > $CUSTOM_RESOURCE_FILE
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: nutius_htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret-nutius
EOF

# Delet initial htpass-secret for CodeReady Containers (user: developer)
#oc delete secret htpass-secret -n openshift-config
#oc delete identity htpasswd_provider:developer

oc create secret generic htpass-secret-nutius --from-file=htpasswd=$HTPASSWD_FILE -n openshift-config
oc apply -f $CUSTOM_RESOURCE_FILE

oc adm policy add-cluster-role-to-user cluster-admin admin
