#
# This Ansible playbook downloads the latest release of the oc-mirror tool and installs it to the local filesystem.
# oc-mirror - 
#
#
# [1] Mirroring images for a disconnected installation using the oc-mirror plugin
#     https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-disconnected.html
#
# [2] OpenShift oc-mirror source code
#     https://github.com/openshift/oc-mirror
#  
# Download links:
# ---------------
# - https://console.redhat.com/openshift/downloads
# - https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
#
#

---
- name: "Update binary file from github.com releases of oc-mirror tool.."
  hosts:
    - localhost
  become: true
  gather_facts: false
  vars:
    # All the artifacts are downloaded to this directory..
    # Feel free to change it to /tmp for example..
    download_dir: "/var/downloads"

    # The destination directory for the binary file..
    destination_directory: "/opt/cli-tools"
    destination_file_name: "oc-mirror"

    # The GitHub repository specific variables..
    repository_owner: "openshift"
    project_name: "oc-mirror"
    release_file_name: "oc-mirror"
    github_repo_url: "https://github.com/{{ repository_owner  }}/{{ project_name }}"


  tasks:
    - name: Ensure the target directory for downloaded files exists ({{ download_dir }})..
      file:
        path: "{{ download_dir }}"
        state: directory

    #
    # Failing with:
    # https://api.github.com/repos/openshift/oc-mirror/releases/latest
    # {
    #   "message": "Not Found",
    #   "documentation_url": "https://docs.github.com/rest/releases/releases#get-the-latest-release"
    # }
    # 
    - name: Get GitHub Releases
      uri:
        url: "https://api.github.com/repos/{{ repository_owner  }}/{{ project_name }}/releases/latest"
        https://api.github.com/repos/openshift/oc-mirror/releases/latest
        return_content: yes
        headers:
          Accept: "application/vnd.github.v3+json"
      register: github_release

    - name: Extract latest tag
      set_fact:
        latest_tag: "{{ github_release.json.tag_name }}"

    - name: Display latest tag
      debug:
        msg: "Latest tag: {{ latest_tag }}"
  
    - name: Download {{ project_name }}
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ latest_tag }}/oc-mirror.tar.gz"        
        dest: "{{ download_dir }}/{{ release_file_name }}"

    - name: Display downloaded version
      debug:
        msg: "{{ release_file_name }} version {{ latest_tag }} downloaded to {{ download_dir }}/{{ release_file_name }}"

#    - name: Move latest release of {{ destination_file_name }} to its destination on local filesystem.. ({{ destination_directory }}/{{ destination_file_name }})
#      ansible.builtin.copy:
#        src: "{{ download_dir }}/{{ release_file_name }}"
#        dest: "{{ destination_directory }}/{{ destination_file_name }}"
#        owner: "root"
#        group: "root"
#        mode: "0755"
