---
- name: Deploy Red Hat Off-line Knowledge Portal (RHOKP)
  hosts: localhost
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - secrets.yaml

  vars:
    registry_host: "registry.redhat.io"
    image: "offline-knowledge-portal/rhokp-rhel9"
    tag: "latest"

    home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Print the access key for RHOKP..
      ansible.builtin.debug:
        msg: "Access Key: {{ rhokp_access_key }}"

    - name: Login to the  Red Hat Registry via podman..
      ansible.builtin.command:
        cmd: "podman login --username {{ db_login }} --password {{ db_passwd }} --verbose {{ registry_host }}"

    - name: Execute the podman system migrate to update ID mappings..
      ansible.builtin.command: podman system migrate
      register: podman_migrate_result
      changed_when: "'Database migrated' in podman_migrate_result.stdout"
      failed_when: 
        - podman_migrate_result.rc != 0
        - "'Error: ' in podman_migrate_result.stderr"

    - name: Pull the image with RHOKP..
      ansible.builtin.command:
        cmd: "podman pull {{ registry_host }}/{{ image }}:{{ tag }}"
      register: pull_result
      changed_when: "'Image is up to date' not in pull_result.stdout"

    - name: Create httpd-ssl directory..
      ansible.builtin.file:
        path: "/var/containers/rhokp/httpd-ssl/certs"
        state: directory
        mode: '0755'

    - name: Create httpd-ssl directory..
      ansible.builtin.file:
        path: "/var/containers/rhokp/httpd-ssl/private"
        state: directory
        mode: '0755'

    - name: Copy certificate to httpd-ssl directory..
      ansible.builtin.copy:
        src: "/var/certificates/rhokp/fullchain.pem"
        dest: "/var/containers/rhokp/httpd-ssl/certs/server.pem"
        mode: '0644'

    - name: Copy private key of certificate to httpd-ssl directory..
      ansible.builtin.copy:
        src: "/var/certificates/rhokp/privkey.pem"
        dest: "/var/containers/rhokp/httpd-ssl/private/server.pem"
        mode: '0644'

    - name: Create directory for Podman Quadlet file if it does not exist..
      ansible.builtin.file:
        path: /etc/containers/systemd/
        state: directory
        mode: '0755'

    - name: Generate the Podman Quadlet file for RHOKP..
      ansible.builtin.template:
        src: rhokp.container.j2
        dest: /etc/containers/systemd/rhokp.container
        mode: '0640'
      notify: Reload systemd and start RHOKP..

  handlers:
    - name: Reload systemd and start RHOKP..
      ansible.builtin.systemd:
        daemon_reload: yes
        name: rhokp.service 
        enabled: yes
        state: restarted