#! /bin/bash -e

HTPASSWD_FILE="/tmp/crc.htpasswd"
echo "Creating : $HTPASSWD_FILE"

# htpasswd
# --------
# -c = Create a new file (the first command to create the file)..
# -B = Use bcrypt encryption for passwords..
# -b = Use batch mode (danger)..

USER="admin"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -c -B -b $HTPASSWD_FILE $USER $PASSWORD

USER="rludva"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD

USER="alice"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD

USER="bob"
PASSWORD=`cat $HOME/.passwd/crc-$USER.passwd`
htpasswd -B -b $HTPASSWD_FILE $USER $PASSWORD
exit

CUSTOM_RESOURCE_FILE="/tmp/customer_resource.yaml"
cat <<EOF > $CUSTOM_RESOURCE_FILE
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: nutius_htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret-nutius
EOF

# Delet initial htpass-secret for CodeReady Containers (user: developer)
#oc delete secret htpass-secret -n openshift-config
#oc delete identity htpasswd_provider:developer

oc create secret generic htpass-secret-nutius --from-file=htpasswd=$HTPASSWD_FILE -n openshift-config
oc apply -f $CUSTOM_RESOURCE_FILE

oc adm policy add-cluster-role-to-user cluster-admin admin
