apiVersion: v1
kind: Pod
metadata:
  name: phppgadmin
  labels:
    app: phppgadmin
  namespace: openshift-workspaces
spec:
  containers:
  - env:
    image: dockage/phppgadmin
    name: phppgadmin
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
