#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

BOLD=$(tput bold)
UNDERLINE=$(tput smul)
BLINK=$(tput blink)
RESET=$(tput sgr0)

INTERVAL=120

function sleepx() {
 count="$1"
 while [ $count -gt 0 ]; do
   echo -ne "${MAGENTA}We are wating for ${count}s..${RESET}\033[0K\r"
	 read -t 1 -s -N 1 input
	 if [ ! -z "$input" ]; then
	   break
	 fi
   ((count--))
  done

  echo -ne "\033[0K\r"
}


clear

omc use .
MUSTGATHER_PATH=$(omc use | head -n 1 | awk '{print $2}' | tr -d '"')
#MUSTGATHER_PATH=$(pwd)

ES_OPERATOR_VERSION=$(yq .metadata.name $MUSTGATHER_PATH/cluster-logging/eo/csv | tr -d '"')
OPENSHIFT_LOGGING_OPERATOR_VERSION=$(yq -r ".items[].spec.clusterServiceVersionNames[0]" $MUSTGATHER_PATH/cluster-logging/install/install_plan)

echo "Environment:"
echo "------------"
echo "${BOLD}- ${RESET}${GREEN}$ES_OPERATOR_VERSION${RESET}"
echo "${BOLD}- ${RESET}${GREEN}$OPENSHIFT_LOGGING_OPERATOR_VERSION${RESET}"
echo
sleepx $INTERVAL

yq --yaml-output 'del(.metadata.managedFields)' $MUSTGATHER_PATH/cluster-logging/clo/cr | bat -l yaml

clear
echo "OpenShift Logging Pods:"
echo "-----------------------"
omc get pods -n openshift-logging -o wide
echo

sleepx $INTERVAL

