---
- name: Fetch Let's Encrypt certificates and deploy them to rhokp host..
  become: true
  hosts: localhost
  vars:
    #
    # ADJUST: 
    # -------
    # - Set the hostname or IP address of your letsencrypt_hostname variable as hostname here. 
    # - This is where the certificates will be fetched from.
    letsencrypt_hostname: letsencrypt.example.com

    #
    # ADJUST: 
    # -------
    # - Set the hostname or IP address of your rhokp_hostname variable as hostname here. 
    # - This is where the generated secrets.yaml will be deployed.
    rhokp_hostname: rhokp.example.com

    #
    # ADJUST: 
    # -------
    # - Set the domain name for which the certificates were issued here.
    # - This is used to construct the path to the certificates on the letsencrypt host.
    domain: "mimir.example.com"

    # Source path on the Let's Encrypt host
    cert_path: "/etc/letsencrypt/live/{{ domain }}"
    
    # Destination path on the RHOKP host
    rhokp_dest_path: "/var/certificates/rhokp-service"

    deploy_user: "{{ lookup('env', 'USER') }}"

    certificates:
      - fullchain.pem
      - privkey.pem
      - chain.pem
      - cert.pem
    
  tasks:
    # Slurp certificates into memory..
    - name: Read certificates from Let's Encrypt host into memory
      ansible.builtin.slurp:
        src: "{{ cert_path }}/{{ item }}"
      register: slurped_certs
      delegate_to: "{{ letsencrypt_hostname }}"
      loop: "{{ certificates }}"
      no_log: true # EXTREMELY IMPORTANT: Prevents printing the private key to the terminal!

    # Prepare the destination directory on the RHOKP host..
    - name: Remove existing certificates directory on RHOKP host
      ansible.builtin.file:
        path: "{{ rhokp_dest_path }}"
        state: absent
      delegate_to: "{{ rhokp_hostname }}"

    - name: Create destination directory on RHOKP host
      ansible.builtin.file:
        path: "{{ rhokp_dest_path }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0755'
      delegate_to: "{{ rhokp_hostname }}"

    # Write certificates from memory directly to the target server..
    - name: Copy certificates from memory to RHOKP host
      ansible.builtin.copy:
        content: "{{ item.content | b64decode }}"
        dest: "{{ rhokp_dest_path }}/{{ item.item }}" # 'item.item' contains the original filename (e.g., cert.pem)
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0600'
      delegate_to: "{{ rhokp_hostname }}"
      loop: "{{ slurped_certs.results }}"
      no_log: true
      loop_control:
        label: "{{ item.item }}" # Prints only the filename to the terminal, not the hidden content