---
- name: Generate and deploy secrets to RHOKP
  hosts: localhost
  gather_facts: no
  
  vars:
    #
    # ADJUST: 
    # -------
    # - Set the hostname or IP address of your cluster in the 'rhokp_hostname' variable. 
    # - This is where the generated secrets.yaml will be deployed.
    rhokp_hostname: "rhokp.example.com"

  vars_prompt:
    - name: db_login
      prompt: "Enter db_login"
      default: "{{ lookup('file', '.variable_db_login', errors='ignore') | default('', true) | trim }}"
      private: no

    - name: db_passwd
      prompt: "Enter db_passwd"
      default: "{{ lookup('file', '.variable_db_passwd', errors='ignore') | default('', true) | trim }}"
      private: no

    - name: rhokp_access_key
      prompt: "Enter rhokp_access_key"
      default: "{{ lookup('file', '.variable_rhokp_key', errors='ignore') | default('', true) | trim }}"
      private: no

  tasks:
    # 1. Save values back to cache 
    - name: Save entered values to local cache files
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "{{ item.dest }}"
        mode: "0600"
      loop:
        - { value: "{{ db_login }}",        dest: ".variable_db_login" }
        - { value: "{{ db_passwd }}",       dest: ".variable_db_passwd" }
        - { value: "{{ rhokp_access_key }}", dest: ".variable_rhokp_key" }
      loop_control:
        label: "{{ item.dest }}" # Shows the file name in the terminal instead of the secret content!

    # 2. Generate and deploy the file
    - name: Create secrets.yaml on the target server
      ansible.builtin.template:
        src: secrets.yaml.j2
        dest: secrets.yaml
        mode: "0600"
      delegate_to: "{{ rhokp_hostname }}"