---
- name: Generate and deploy secrets to RHOKP
  hosts: localhost
  gather_facts: no
  
  vars:
    #
    # ADJUST: 
    # -------
    # - Set the hostname or IP address of your cluster in the 'rhokp_hostname' variable. 
    # - This is where the generated secrets.yaml will be deployed.
    rhokp_hostname: "rhokp.example.com"

    # Target directory on the remote server
    secret_dir: "/var/containers/rhokp-service"

  vars_prompt:
    - name: db_login
      prompt: "Enter Registry User (db_login)"
      default: "{{ lookup('file', '.variable_db_login', errors='ignore') | default('', true) | trim }}"
      private: no

    - name: db_passwd
      prompt: "Enter Registry Password (db_passwd)"
      default: "{{ lookup('file', '.variable_db_passwd', errors='ignore') | default('', true) | trim }}"
      private: yes # Hides the password input in the terminal

    - name: rhokp_access_key
      prompt: "Enter RHOKP Access Key"
      default: "{{ lookup('file', '.variable_rhokp_key', errors='ignore') | default('', true) | trim }}"
      private: yes

  tasks:
    # 1. Save entered values to local cache files for future runs..
    - name: Save entered values to local cache files
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "{{ item.dest }}"
        mode: "0600"
      loop:
        - { value: "{{ db_login }}",         dest: ".variable_db_login" }
        - { value: "{{ db_passwd }}",        dest: ".variable_db_passwd" }
        - { value: "{{ rhokp_access_key }}", dest: ".variable_rhokp_key" }
      loop_control:
        label: "{{ item.dest }}"

    # 2. Ensure the target directory exists on the remote server (requires root)..
    - name: Ensure target directory exists on remote server
      ansible.builtin.file:
        path: "{{ secret_dir }}"
        state: directory
        mode: "0750"
      delegate_to: "{{ rhokp_hostname }}"
      become: yes 

    # 3. Generate the secret files directly on the server..
    - name: Create secret files on the target server
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "{{ secret_dir }}/{{ item.filename }}"
        mode: "0600" # Crucial: Only root can read these files
      loop:
        - { value: "{{ db_login }}",         filename: ".REGISTRY_USER" }
        - { value: "{{ db_passwd }}",        filename: ".REGISTRY_PASS" }
        - { value: "{{ rhokp_access_key }}", filename: ".RHOKP_ACCESS_KEY" }
      loop_control:
        label: "{{ item.filename }}"
      delegate_to: "{{ rhokp_hostname }}"
      become: yes